Repository raffaeldutra/docker.raffaeldutra.github.io, pull requests merged in 2023-08, with the labels that each got.

#3 Closes #1. Alterado comando para rodar containers
  docs/c1/interacting-containers.md
  docs/c1/managing-containers.md
  docs/c1/manipulate-containers.md
  docs/c1/running-containers.md
  docs/c2/creating-image-no-dockerfile.md
  docs/c2/creating-image.md
  docs/c3/storage-drivers.md
  docs/installing.md
Labels: documentation, container

#5 Closes #4. Ajustado url para repositório
  docs/index.md
Labels: documentation

#7 Closes #6. Alterado comando para build de imagem
  docs/c2/creating-image.md
Labels: documentation, image

#9 Closes #8. CNAME para dentro do diretório docs
  docs/CNAME
Labels: enhancement

#12 Fix #11. Adicionado conteúdo para volumes
  docs/c3/volumes.md
Labels: bug, documentation

#13 Fix #10. Imagens estavam faltando
  docs/c3/images/container-layers.jpg
  docs/c3/images/sharing-layers.jpg
Labels: bug, documentation

#19 Closes #15. Trocadas palavras no primeiro paragrafo
  docs/index.md
Labels: documentation

#20 Closes #16 Ajuste de palavras no terceiro paragrafo
  docs/index.md
Labels: documentation
